name: axent-note

services:
  app:
    container_name: axent
    build:
      target: production
    command: "/bin/sh -c 'pnpm install && pnpm dev --host'"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/next
    # env_file:
    #   - .env
